language: bash

before_install: # Download and install Terraform for us on the container
  - wget https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_linux_amd64.zip
  - unzip terraform_0.14.8_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.14.8_linux_amd64.zip
  
jobs:
  include:
    - stage: terraform plan # When a Pull Request is created - Validate our plan
      if: type IN (pull_request)
      script:
        - terraform init
        - terraform plan -var-file=env\dev\vars.tfvars -out build.plan

    - stage: terraform apply # Merge our PR - Deploy it!
      if: type IN (push) and branch = master
      script:
        - terraform init
        - terraform plan -var-file=env\dev\vars.tfvars -out build.plan
        - terraform apply build.plan
