language: bash

env:
  global:
    secure: T91tSY26KS/x+Vj+yFAtsPpY6j310UCZQ8OAjpJ9AfqGQQE/2Dw3X2a3Oj6zUYJE75GHxjvcyt1WBA47lQ5jZ3UaMBV1mDmQBbx+gjHlZ5pQsueDr+kspRGHveISksfSV6ui6MMMaZ14h4P/KirwQKuC1KVaP4gBGJHtcYhG4EqofGGmpxD2HFomIZJeN81KlHKGAiL1MSqIYj4dewWRzCs566uJfX45AFkqZYmVw90vJjqpKbpku6ZM2Jvx4W33eM2BEX3wSzS6SEJg4bGCSQLEicXWs39OV2v7mCiULmm4+nM8umYZdtLbadUKxEHagVOrGkDAbxg6F+h7RtO4S1Qn+OP1zqiQMXoE3tNpwfZojOKr21cqTSrwcBy0rcrccwzAlClSYP7rSS2ou8/0zhnzEst2HFKZFLMaq05+KazU12uFjWb5vzP9uxA2AjbqQD+FIlflWpH2J0KbJEHLTsWdOgQI/yToAVj3JYn7z5+TfBlVXHNh11muL95KGfqfRrxhSaRaLWBoYPy6zQg9DH0Q/FfjLq3c8wQsod5hKCkWtbmt+VtdalnTNcCTVTI76QoGlGB9WkzJ3idBbybx213rTzD/vJKAnEcW2NKdhFsziYRYJhNIRNwKxXw+4VQN4V2AGh+Qne4y/kux+LMp+u1jjf4PbA+LIt1iyrucVyQ=

before_install:
- wget https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_linux_amd64.zip
- unzip terraform_0.14.8_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_0.14.8_linux_amd64.zip
- echo $TRAVIS_BUILD_DIR
- echo "$(pwd)"
- echo "$(ls -l)"
- openssl aes-256-cbc -k "123" -in sa-key.json.enc -out sa-key2.json -d
- echo "$(ls -l)"

jobs:
  include:
  - stage: terraform plan
    if: type IN (pull_request)
    script:
    - terraform init
    - terraform plan -var-file=env\dev\vars.tfvars -out build.plan
  - stage: terraform apply
    if: type IN (push) and branch = master
    script:
    - terraform init
    - terraform plan -var-file=env\dev\vars.tfvars -out build.plan
    - terraform apply build.plan

